Test Code

In [1]:
test = "Hello World"
print(test)

Hello World


In [2]:
#importing Numpy Library
import numpy as np

In [3]:
#creation of 1-Dimensional Array
one_dimensional_arr = np.array([10,12])
print(one_dimensional_arr)

[10 12]


# create a numpy array

In [4]:
# create a numpy array
a = np.array([1,2,3])
print(a)
b = np.arange(3)
print(b)
c = np.arange(1,20,3)
print(c)

[1 2 3]
[0 1 2]
[ 1  4  7 10 13 16 19]


In [5]:
#linespaced np array
lin_spaced_arr = np.linspace(0,100,5)
print(lin_spaced_arr)

[  0.  25.  50.  75. 100.]


In [6]:
line_spaced_arr_int = np.linspace(0,100,5,dtype = int)
print(line_spaced_arr_int)

[  0  25  50  75 100]


In [7]:
c_int = np.arange(1,20,3,dtype = int)
print(c_int)

[ 1  4  7 10 13 16 19]


In [8]:
b_float = np.arange(3,dtype = float)
print(b_float)

[0. 1. 2.]


In [9]:
char_arr = np.array(['Welcome to Math for ML'])
print(char_arr)
print(char_arr.dtype)

['Welcome to Math for ML']
<U22


In [10]:
ones_arr = np.ones(3)
print(ones_arr)

[1. 1. 1.]


In [11]:
zeros_arr = np.zeros(3)
print(zeros_arr)

[0. 0. 0.]


In [12]:
empty_arr = np.empty(3)
print(empty_arr)

[0. 0. 0.]


In [13]:
rand_arr = np.random.rand(3)
print(rand_arr)

[0.18700487 0.49443588 0.87102022]


# Multidimensional Arrays

In [14]:
#create a 2D array
two_dim_arr = np.array([[1,2,3],[4,5,6]])
print(two_dim_arr)

[[1 2 3]
 [4 5 6]]


In [15]:
one_dim_arr = np.array([1,2,3,4,5,6])
multi_dim_arr = np.reshape(one_dim_arr,(2,3))
print(multi_dim_arr)

[[1 2 3]
 [4 5 6]]


In [16]:
multi_dim_arr.ndim

2

In [17]:
multi_dim_arr.shape


(2, 3)

In [18]:
multi_dim_arr.size

6

# Array math operations

In [19]:
arr_1 = np.array([2, 4, 6])
arr_2 = np.array([1, 3, 5])

# Adding two 1-D arrays
addition = arr_1 + arr_2
print(addition)

# Subtracting two 1-D arrays
subtraction = arr_1 - arr_2
print(subtraction)

# Multiplying two 1-D arrays elementwise
multiplication = arr_1 * arr_2
print(multiplication)

[ 3  7 11]
[1 1 1]
[ 2 12 30]


In [20]:
#multiplying vector with scalar

vector = np.array([1, 2])
vector * 1.6

array([1.6, 3.2])

# indexing and Slicing

In [21]:
#indexing
# Select the third element of the array. Remember the counting starts from 0.
a = ([1, 2, 3, 4, 5])
print(a[2])

# Select the first element of the array.
print(a[0])

3
1


In [22]:
# Indexing on a 2-D array
two_dim = np.array(([1, 2, 3],
          [4, 5, 6], 
          [7, 8, 9]))

# Select element number 8 from the 2-D array using indices i, j.
print(two_dim[2][1])

8


In [23]:
# Slice the array a to get the array [2,3,4]
sliced_arr = a[1:4]
print(sliced_arr)

[2, 3, 4]


In [24]:
# Slice the array a to get the array [1,2,3]
sliced_arr = a[:3]
print(sliced_arr)

[1, 2, 3]


In [25]:
# Slice the array a to get the array [3,4,5]
sliced_arr = a[2:]
print(sliced_arr)

[3, 4, 5]


In [26]:
# Slice the array a to get the array [1,3,5]
sliced_arr = a[::2]
print(sliced_arr)

[1, 3, 5]


In [27]:
# Note that a == a[:] == a[::]
print(a == a[:] == a[::])

True


In [28]:
# Slice the two_dim array to get the first two rows
sliced_arr_1 = two_dim[0:2]
sliced_arr_1

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
# Similarily, slice the two_dim array to get the last two rows
sliced_two_dim_rows = two_dim[1:3]
print(sliced_two_dim_rows)

[[4 5 6]
 [7 8 9]]


In [30]:
sliced_two_dim_cols = two_dim[:,1]
print(sliced_two_dim_cols)

[2 5 8]


# Stacking

In [31]:
a1 = np.array([[1,1], 
               [2,2]])
a2 = np.array([[3,3],
              [4,4]])
print(f'a1:\n{a1}')
print(f'a2:\n{a2}')

a1:
[[1 1]
 [2 2]]
a2:
[[3 3]
 [4 4]]


In [32]:
# Stack the arrays vertically
vert_stack = np.vstack((a1, a2))
print(vert_stack)

[[1 1]
 [2 2]
 [3 3]
 [4 4]]


In [33]:
# Stack the arrays horizontally
horz_stack = np.hstack((a1, a2))
print(horz_stack)

[[1 1 3 3]
 [2 2 4 4]]
