# Solving Linear Systems: 3 Variables

In [1]:
import numpy as np

In [2]:
A = np.array([
        [4, -3, 1],
        [2, 1, 3],
        [-1, 2, -5]
    ], dtype=np.dtype(float))

b = np.array([-10, 0, 17], dtype=np.dtype(float))

print("Matrix A:")
print(A)
print("\nArray b:")
print(b)

Matrix A:
[[ 4. -3.  1.]
 [ 2.  1.  3.]
 [-1.  2. -5.]]

Array b:
[-10.   0.  17.]


In [3]:
print(f"Shape of A: {np.shape(A)}")
print(f"Shape of b: {np.shape(b)}")

Shape of A: (3, 3)
Shape of b: (3,)


In [4]:
x = np.linalg.solve(A,b)
print(f"Solution: {x}")

Solution: [ 1.  4. -2.]


In [5]:
d = np.linalg.det(A)
print(f"Determinant of matrix A:{d:.2f}")

Determinant of matrix A:-60.00


# Solving System of Linear Equations using Row Reduction

In [6]:
A_system = np.hstack((A, b.reshape((3, 1))))

print(A_system)

[[  4.  -3.   1. -10.]
 [  2.   1.   3.   0.]
 [ -1.   2.  -5.  17.]]


In [7]:
# exchange row_num of the matrix M with its multiple by row_num_multiple
def MultiplyRow(M, row_num, row_num_multiple):
    M_new = M.copy()
    M_new[row_num] = M_new[row_num] * row_num_multiple
    return M_new
print("Original matrix:")
print(A_system)
print("\nMatrix after its third row is multiplied by 2:")
print(MultiplyRow(A_system,2,2))

Original matrix:
[[  4.  -3.   1. -10.]
 [  2.   1.   3.   0.]
 [ -1.   2.  -5.  17.]]

Matrix after its third row is multiplied by 2:
[[  4.  -3.   1. -10.]
 [  2.   1.   3.   0.]
 [ -2.   4. -10.  34.]]


In [8]:
# exchange row_num_1 and row_num_2 of the matrix M
def SwapRows(M, row_num_1, row_num_2):
    M_new = M.copy()
    M_new[[row_num_1, row_num_2]] = M_new[[row_num_2, row_num_1]]
    return M_new
print("Original matrix:")
print(A_system)
print("\nMatrix after exchange its first and third rows:")
print(SwapRows(A_system,0,2))

Original matrix:
[[  4.  -3.   1. -10.]
 [  2.   1.   3.   0.]
 [ -1.   2.  -5.  17.]]

Matrix after exchange its first and third rows:
[[ -1.   2.  -5.  17.]
 [  2.   1.   3.   0.]
 [  4.  -3.   1. -10.]]


In [9]:
A_ref = SwapRows(A_system,0,2)
print(A_ref)

[[ -1.   2.  -5.  17.]
 [  2.   1.   3.   0.]
 [  4.  -3.   1. -10.]]


In [10]:
def AddRows(M, row_num_1, row_num_2, row_num_1_multiple):
    M_new = M.copy()
    M_new[row_num_2] = row_num_1_multiple * M_new[row_num_1] + M_new[row_num_2]
    return M_new
print("Original matrix:")
print(A_system)
print("\nMatrix after exchange of the third row with the sum of itself and second row multiplied by 1/2:")
print(AddRows(A_system,1,2,1/2))

Original matrix:
[[  4.  -3.   1. -10.]
 [  2.   1.   3.   0.]
 [ -1.   2.  -5.  17.]]

Matrix after exchange of the third row with the sum of itself and second row multiplied by 1/2:
[[  4.   -3.    1.  -10. ]
 [  2.    1.    3.    0. ]
 [  0.    2.5  -3.5  17. ]]


In [11]:
A_ref = AddRows(A_ref,0,1,2)
print(A_ref)

[[ -1.   2.  -5.  17.]
 [  0.   5.  -7.  34.]
 [  4.  -3.   1. -10.]]


In [12]:
A_ref = AddRows(A_ref,0,2,4)
print(A_ref)

[[ -1.   2.  -5.  17.]
 [  0.   5.  -7.  34.]
 [  0.   5. -19.  58.]]


In [13]:
A_ref = AddRows(A_ref,1,2,-1)
print(A_ref)

[[ -1.   2.  -5.  17.]
 [  0.   5.  -7.  34.]
 [  0.   0. -12.  24.]]


In [14]:
A_ref = MultiplyRow(A_ref,2,-1/12)
print(A_ref)

[[-1.  2. -5. 17.]
 [ 0.  5. -7. 34.]
 [-0. -0.  1. -2.]]


In [15]:
x_3 = -2
x_2 = (A_ref[1,3] - A_ref[1,2] * x_3) / A_ref[1,1]
x_1 = (A_ref[0,3] - A_ref[0,2] * x_3 - A_ref[0,1] * x_2) / A_ref[0,0]

print(x_1, x_2, x_3)

1.0 4.0 -2


#  System of Linear Equations with No Solutions

In [16]:
A_2= np.array([
        [1, 1, 1],
        [0, 1, -3],
        [2, 1, 5]
    ], dtype=np.dtype(float))

b_2 = np.array([2, 1, 0], dtype=np.dtype(float))

d_2 = np.linalg.det(A_2)

print(f"Determinant of matrix A_2: {d_2:.2f}")

Determinant of matrix A_2: 0.00


In [17]:
A_2_system = np.hstack((A_2, b_2.reshape((3, 1))))
print(A_2_system)

[[ 1.  1.  1.  2.]
 [ 0.  1. -3.  1.]
 [ 2.  1.  5.  0.]]


In [18]:
A_2_ref = AddRows(A_2_system,0,2,-2)
print(A_2_ref)

[[ 1.  1.  1.  2.]
 [ 0.  1. -3.  1.]
 [ 0. -1.  3. -4.]]


In [19]:
A_2_ref = AddRows(A_2_ref,1,2,1)
print(A_2_ref)

[[ 1.  1.  1.  2.]
 [ 0.  1. -3.  1.]
 [ 0.  0.  0. -3.]]


# System of Linear Equations with Infinite Number of Solutions

In [21]:
b_3 = np.array([2,1,3])

In [22]:
A_3_system = np.hstack((A_2,b_3.reshape((3,1))))
print(A_3_system)

[[ 1.  1.  1.  2.]
 [ 0.  1. -3.  1.]
 [ 2.  1.  5.  3.]]


In [23]:
A_3_ref = AddRows(A_3_system,0,2,-2)
print(A_3_ref)

[[ 1.  1.  1.  2.]
 [ 0.  1. -3.  1.]
 [ 0. -1.  3. -1.]]


In [24]:
A_3_ref = AddRows(A_3_ref,1,2,1)
print(A_3_ref)

[[ 1.  1.  1.  2.]
 [ 0.  1. -3.  1.]
 [ 0.  0.  0.  0.]]
